### ISSUE TITLE
Add POST /v1/chains/<chain_id>/transactions/<safe_address>/propose

### ISSUE THREAD

**Issue by fmrsabino** [safe-global/safe-client-gateway-nest#254]

**Comment by hectorgomezv** [comment]
We need to return the proposed/created transaction in the response, by getting it from the transaction service by id. I did some work to cover part of the endpoint functionality in [the related branch]([propose-transactions](https://github.com/5afe/safe-client-gateway-nest/tree/propose-transactions)). I'm marking this issue blocked by [the transaction service one implementing the retrieval of transactions by id](https://github.com/safe-global/safe-transaction-service/pull/1365).
