### ISSUE TITLE
Mount cache in Docker image

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-client-gateway-nest#308]
- Change the `Dockerfile` definition to avoid Docker cache rewrites in each build, and decrease the build time in the CI pipeline. Please refer to https://github.com/safe-global/safe-gelato-relay-service/pull/89 for details.

**Comment by fmrsabino** [comment]
I would say that these are two different issues. The Node.js version is independent of caching dependencies.

**Comment by hectorgomezv** [comment]
I agree, I've just moved the Node update to a separate issue: https://github.com/safe-global/safe-client-gateway-nest/issues/309
