### ISSUE TITLE
Get balances endpoint, previously type now tokenType

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-client-gateway-nest#311]
When fetching safe balances we are using `type` on the old backend but this has changes to `tokenType` on the revamped client gateway. We need to check if this can cause some compatibility issues.

New client gateway:

`curl --location 'https://safe-client-nest.staging.5afe.dev/v1/chains/1/safes/0xB88F61E6FbdA83fbfffAbE364112137480398018/balances/eur'`

Old client gateway

`curl --location 'https://safe-client.staging.5afe.dev/v1/chains/1/safes/0xB88F61E6FbdA83fbfffAbE364112137480398018/balances/eur'`

Also when specifying the new client gateway when setting the project locally the /assets page crashes:

<img width="852" alt="Screenshot 2023-05-08 at 09 25 28" src="https://user-images.githubusercontent.com/92332710/236761765-95ee169c-2b06-4e9b-8932-67d27dc71a32.png">

**Comment by fmrsabino** [comment]
I can confirm that this is an issue. The field should be `type` and not `tokenType`
