### ISSUE TITLE
[safes/{safe} endpoint] status code 404 returned on Goerli

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-client-gateway-nest#326]
A status code 404 is returned when fetching any of my safes on this chain. 

Note: No issues when fetching safes on mainnet on mainnet or polygon neither on the old backend.

New client gateway:

`curl --location 'https://safe-client-nest.staging.5afe.dev/v1/chains/5/safes/0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C'`

Old client gateway:

`curl --location 'https://safe-client.staging.5afe.dev/v1/chains/5/safes/0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C'`

Actual result on nest cg:

`{
    "code": 404,
    "message": "An error occurred"
}`

ui:

<img width="402" alt="Screenshot 2023-05-11 at 19 01 16" src="https://github.com/safe-global/safe-client-gateway-nest/assets/92332710/96eed74e-4a29-4406-b073-29266245ddd8">

**Comment by fmrsabino** [comment]
I can confirm this bug. The issue is that in the new service it fails if it cannot find a known address for the Safe's Fallback Handler. The correct implementation should be if there is no known address for it, to just return the address.
