### ISSUE TITLE
[{safe}/transactions/history endpoint] status code 429 returned for safe with many nft transfers

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-client-gateway-nest#327]
A status code 429 is returned when trying to fetch the balances of this mainnet safe.

New client gateway:

`curl --location 'https://safe-client-nest.staging.5afe.dev/v1/chains/1/safes/0xB88F61E6FbdA83fbfffAbE364112137480398018/transactions/history'`

Old client gateway:

`curl --location 'https://safe-client.staging.5afe.dev/v1/chains/1/safes/0xB88F61E6FbdA83fbfffAbE364112137480398018/transactions/history'`

Actual result on nest cg:

`{
    "code": 429,
    "message": "An error occurred"
}`

ui:

https://github.com/safe-global/safe-client-gateway-nest/assets/92332710/3b838da0-66d8-4655-b539-ce65df7a9902

**Comment by fmrsabino** [comment]
We will be adding some more logs to debug this issue on `staging`: https://github.com/safe-global/safe-client-gateway-nest/pull/346
