### ISSUE TITLE
[Post /data-decoder] 400 bad request - 42  "Validation failed"

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway-nest#334]
**Request**: Post https://safe-client-nest.staging.5afe.dev/v1/chains/137/data-decoder
**Status code**  : 400 Bad Request
**Payload** : `{"data":"0x42842e0e000000000000000000000000b412684f4f0b5d27cc4a4d287f42595ab3ae124d000000000000000000000000b412684f4f0b5d27cc4a4d287f42595ab3ae124d0000000000000000000000000000000000000000000000000000000000000001"}`

**Response** : `{"message":"Validation failed","code":42,"arguments":[]}`

Steps from the Web client side:
1. go to the https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev/balances/nfts?safe=matic:0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D
2. try to send NFT 
3. Go to the Review NFT transaction
<img width="593" alt="image" src="https://github.com/safe-global/safe-client-gateway-nest/assets/338622/e56eb3ac-f3ed-40b6-b4d0-531edc214694">

Response from the old CGW: `{"method":"safeTransferFrom","parameters":[{"name":"from","type":"address","value":"0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D"},{"name":"to","type":"address","value":"0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D"},{"name":"tokenId","type":"uint256","value":"1"}]}`

--------
**Same for the next payload**  (this is add spending limits details): `0x8d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001eb00b412684f4f0b5d27cc4a4d287f42595ab3ae124d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024610b59250000000000000000000000001fb403834c911eb98d56e74f5182b0d64c3b3b4d001fb403834c911eb98d56e74f5182b0d64c3b3b4d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024e71bdf410000000000000000000000004c3c38a459f0baabb763290111b66ed01b5fefa2001fb403834c911eb98d56e74f5182b0d64c3b3b4d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a4beaeb3880000000000000000000000004c3c38a459f0baabb763290111b66ed01b5fefa20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000005a00000000000000000000000000000000000000000000000000000000001ac4d6c000000000000000000000000000000000000000000` 

response : validation failed 
Expected response :
`{
    "method": "multiSend",
    "parameters": [
        {
            "name": "transactions",
            "type": "bytes",
            "value": "0x00b412684f4f0b5d27cc4a4d287f42595ab3ae124d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024610b59250000000000000000000000001fb403834c911eb98d56e74f5182b0d64c3b3b4d001fb403834c911eb98d56e74f5182b0d64c3b3b4d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024e71bdf410000000000000000000000004c3c38a459f0baabb763290111b66ed01b5fefa2001fb403834c911eb98d56e74f5182b0d64c3b3b4d000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a4beaeb3880000000000000000000000004c3c38a459f0baabb763290111b66ed01b5fefa200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000005a00000000000000000000000000000000000000000000000000000000001ac4d6f",
            "valueDecoded": [
                {
                    "operation": 0,
                    "to": "0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D",
                    "value": "0",
                    "data": "0x610b59250000000000000000000000001fb403834c911eb98d56e74f5182b0d64c3b3b4d",
                    "dataDecoded": {
                        "method": "enableModule",
                        "parameters": [
                            {
                                "name": "module",
                                "type": "address",
                                "value": "0x1Fb403834C911eB98d56E74F5182b0d64C3b3b4D"
                            }
                        ]
                    }
                },
                {
                    "operation": 0,
                    "to": "0x1Fb403834C911eB98d56E74F5182b0d64C3b3b4D",
                    "value": "0",
                    "data": "0xe71bdf410000000000000000000000004c3c38a459f0baabb763290111b66ed01b5fefa2",
                    "dataDecoded": {
                        "method": "addDelegate",
                        "parameters": [
                            {
                                "name": "delegate",
                                "type": "address",
                                "value": "0x4c3c38a459F0bAABB763290111B66ed01b5fEfA2"
                            }
                        ]
                    }
                },
                {
                    "operation": 0,
                    "to": "0x1Fb403834C911eB98d56E74F5182b0d64C3b3b4D",
                    "value": "0",
                    "data": "0xbeaeb3880000000000000000000000004c3c38a459f0baabb763290111b66ed01b5fefa200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000005a00000000000000000000000000000000000000000000000000000000001ac4d6f",
                    "dataDecoded": {
                        "method": "setAllowance",
                        "parameters": [
                            {
                                "name": "delegate",
                                "type": "address",
                                "value": "0x4c3c38a459F0bAABB763290111B66ed01b5fEfA2"
                            },
                            {
                                "name": "token",
                                "type": "address",
                                "value": "0x0000000000000000000000000000000000000000"
                            },
                            {
                                "name": "allowanceAmount",
                                "type": "uint96",
                                "value": "1000000000000000000"
                            },
                            {
                                "name": "resetTimeMin",
                                "type": "uint16",
                                "value": "1440"
                            },
                            {
                                "name": "resetBaseMin",
                                "type": "uint32",
                                "value": "28069231"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}`

**Comment by JagoFigueroa** [comment]
Unfortunately I am having the same issue as Lili after the fix was merged 😢 


https://github.com/safe-global/safe-client-gateway-nest/assets/92332710/20b7239c-8fc0-442d-a93c-239edb35b3ed

Will reopen this for further 👀

**Comment by fmrsabino** [comment]
> Unfortunately I am having the same issue as Lili after the fix was merged 😢
> 
>  issue.mp4 
> Will reopen this for further 👀

@JagoFigueroa can you share the request and response?
