### ISSUE TITLE
[Get /queued] Queued endpoint returns already executed txs

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway-nest#335]
**Request**: Get https://safe-client-nest.staging.5afe.dev/v1/chains/137/safes/0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D/transactions/queued 

**The current safe nonce** : 84

**Response:**  The tx starting from the nonce 18 is returned. It seems that all cancelled tx( replaced by another tx) are returned in the response

Steps from the web wallet side:
1. go to the https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev/transactions/queue?safe=matic:0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D
Expected result : https://safe-client.staging.5afe.dev/v1/chains/137/safes/0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D/transactions/queued 
The safe contain only 2 txs with the same nonce 84 in the queued list

**Comment by fmrsabino** [comment]
I can confirm this issue. It's using the Safe Transaction Service endpoint: `GET /api/v1/safes/0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D/multisig-transactions/?executed=false&trusted=true&ordering=nonce` which returns cancelled transactions (as they were also not executed).

It should instead use `nonce__gte` in the same endpoint
