### ISSUE TITLE
[Get /queued and /history] pagination doesn't work on web client 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway-nest#336]
**Request from the client side** : `http://safe-client-nest.staging.5afe.dev/v1/chains/137/safes/0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D/transactions/history?cursor=limit%3D20%26offset%3D20`

**Payload** : cursor=limit%3D20%26offset%3D20 

**Same request when old CGW was used** : `https://safe-client.staging.5afe.dev/v1/chains/137/safes/0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D/transactions/history?cursor=limit%3D20%26offset%3D20&timezone_offset=0`

Steps from the client side 
1. open https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev/transactions/history?safe=matic:0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D
2. scroll the history down
 Expected result: Make sure that pagination works as expected

**Comment by fmrsabino** [comment]
The paginated request from the client side does work: https://safe-client-nest.staging.5afe.dev/v1/chains/137/safes/0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D/transactions/history?cursor=limit%3D20%26offset%3D20

Is there any other issue logged on the client side?

**Comment by liliya-soroka** [comment]
hm, might be env issue : 
<img width="1321" alt="image" src="https://github.com/safe-global/safe-client-gateway-nest/assets/338622/72233920-2447-4407-bd51-95ed57dfe63c">

**Comment by fmrsabino** [comment]
> hm, might be env issue : <img alt="image" width="1321" src="https://user-images.githubusercontent.com/338622/238653040-72233920-2447-4407-bd51-95ed57dfe63c.png">

Ok this is an issue on the backend side. The following HTTPS request https://safe-client-nest.staging.5afe.dev/v1/chains/137/safes/0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D/transactions/history?cursor=limit%3D20%26offset%3D20 returns the pagination links as HTTP.

**Comment by fmrsabino** [comment]
After taking a deeper look it seems that we are correctly assigning the protocol to be used on the service side.

I will coordinate with devops on this one as it seems to be an issue with the deployment.

**Comment by JagoFigueroa** [comment]
Hi there! WIll repoen this ticket if that is okay. I found a couple of mainnet safes returning a status code 500 when pagination is performed on UI:

`curl 'https://safe-client-nest.staging.5afe.dev/v1/chains/1/safes/0xF7f52Dd34bc21eDA08c0b804C7c1dbc48375820f/transactions/history?cursor=limit%3D20%26offset%3D20' \
  -H 'sec-ch-ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"' \
  -H 'Referer: https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev/' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed`

`curl 'https://safe-client-nest.staging.5afe.dev/v1/chains/1/safes/0xBEFA89D90c112A416139F42046Cc2d4A8a308815/transactions/history?cursor=limit%3D20%26offset%3D20' \
  -H 'sec-ch-ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"' \
  -H 'Referer: https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev/' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed`

Response:

`{
    "message": "Validation failed",
    "code": 42,
    "arguments": []
}`

**Comment by JagoFigueroa** [comment]
Por supuesto! closing this
