### ISSUE TITLE
[{{safe}}/collectibles endpoint] status code 500 returned for Goerli safe with NFTs

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-client-gateway-nest#356]
A status code 500 is returned when trying to fetch the collectibles for one of my test safes with NFTs on Goerli.

**Steps to reproduce:**

Execute this curl request:

`curl 'https://safe-client-nest.staging.5afe.dev/v2/chains/5/safes/0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C/collectibles' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Origin: https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev' \
  -H 'Referer: https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed`

**Actual result on nest cg:**

Status code 500 is returned

`{"message":"Validation failed","code":42,"arguments":[]}`

![Screenshot 2023-05-23 at 13 27 56](https://github.com/safe-global/safe-client-gateway-nest/assets/92332710/9ca893ff-c324-49af-ac4c-4422d9bb48eb)

**Expected result on nest cg:**

Same response as when executing: 

`curl --location 'https://safe-client.staging.5afe.dev/v1/chains/5/safes/0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C/balances/EUR?trusted=true' \
--header 'Accept: application/json'`

**Comment by hectorgomezv** [comment]
This is caused because validation fails when validating Transaction Service response for `Collectible.imageUri`. This field  has an schema validation: `imageUri: { type: 'string', nullable: true, default: null, format: 'uri' }` but the field could contains also a [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs).

By instance, the Safe in the example request contains an item which has 
```
"imageUri": "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjg5IiBoZWlnaHQ9IjE1MCIgdmlld0JveD0iMCAwIDI4OSAxNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHN0eWxlPkBmb250LWZhY2V7Zm9udC1mYW1pbHk6IkNhcHN1bGVzLTUwMCI7c ...
```

This would be fixed by relaxing the schema requirements by deleting `format: 'uri'` from the definition.

**Comment by hectorgomezv** [comment]
Besides that case, other malformed URIs are found in the Transaction Service:
`https://ipfs.io/ipfs/QmaVqhfo8Ch19JJxbRAhPJYHo3KwUiBjq3EPardLPJRcKU/NFT DE TESTNET.png` which are making the CGW to fail as well.

**Comment by fmrsabino** [comment]
> This is caused because validation fails when validating Transaction Service response for `Collectible.imageUri`. This field has an schema validation: `imageUri: { type: 'string', nullable: true, default: null, format: 'uri' }`. The requested Safe contains an item with `imageUri: https://ipfs.io/ipfs/QmaVqhfo8Ch19JJxbRAhPJYHo3KwUiBjq3EPardLPJRcKU/NFT DE TESTNET.png` which is making the CGW to fail because that URL is not well-formed.
> 
> I'd say this behavior is correct, since we are validating the correctness of that field (even if the Transaction Service allows that URI). I'd like to know @fmrsabino opinion on this. We need to decide between closing the issue or relaxing the validation for these cases 🤔

I'm leaning towards relaxing the validation on this field to match what was already provided by the old CGW. They should be considered valid URIs where you just have `scheme:path`. It's hard to say if the path should be considered valid in this example. It applies to both `imageUri` and `uri`
