### ISSUE TITLE
[transactions/{{safeAddress}}/preview endpoint] new addressInfoIndex object on response body

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-client-gateway-nest#362]
When executing the same preview request between og and nest cg I see a new `addressInfoIndex` object that it is only present in nest cg (let me know if this is expected/not an issue and we can close the ticket).

**Steps to reproduce**
Execute these 2 curl request with valid and the same data from postman and compare

**Nest cg curl request**
`curl --location 'https://safe-client-nest.staging.5afe.dev/v1/chains/1/transactions/0x38cCa36D45aE54e661fdb8a4462795142dC4C0Eb/preview' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
  "to": "0x6810e776880C02933D47DB1b9fc05908e5386b96",
  "data": "0xa9059cbb000000000000000000000000b88f61e6fbda83fbfffabe364112137480398018000000000000000000000000000000000000000000000000004c37d8c85d99ae",
  "value": "0",
  "operation": 0
}'`

**og client gateway request**
`curl --location 'https://safe-client.staging.5afe.dev/v1/chains/1/transactions/0x38cCa36D45aE54e661fdb8a4462795142dC4C0Eb/preview' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
  "to": "0x6810e776880C02933D47DB1b9fc05908e5386b96",
  "data": "0xa9059cbb000000000000000000000000b88f61e6fbda83fbfffabe364112137480398018000000000000000000000000000000000000000000000000004c37d8c85d99ae",
  "value": "0",
  "operation": 0
}'`

**obtained result**
New `addressInfoIndex` object with the recipient address + name + logo 

`        "addressInfoIndex": {
            "0xB88F61E6FbdA83fbfffAbE364112137480398018": {
                "value": "0xB88F61E6FbdA83fbfffAbE364112137480398018",
                "name": null,
                "logoUri": null
            }
        }`

**Comment by hectorgomezv** [comment]
This should be solved when https://github.com/safe-global/safe-client-gateway-nest/issues/367 is merged, it seems it's the same issue 👍
