### ISSUE TITLE
Add TransactionDetails mappers tests

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-client-gateway-nest#368]
At the moment we are covering `MultisigTransactionDetailsMapper`, `ModuleTransactionDetailsMapper`, and `TransferDetailsMapper` by just using _black box_ tests from the controller perspective (`transactions.controller.spec.ts`).

Given the complexity of some mappings contained in those classes, it would be nice to have specific unit test classes which cover all the possible flows in the mappers. So this issue aims to:
- Create a unit tests class for `MultisigTransactionDetailsMapper` specifically.
- Create a unit tests class for `ModuleTransactionDetailsMapper` specifically.
- Create a unit tests class for `TransferDetailsMapper` specifically.

**Comment by iamacook** [comment]
For reference when tackling this, we should check that [rejectors are retrieved from both queued/executed transactions](https://github.com/safe-global/safe-client-gateway-nest/pull/460). It would also be worth testing against multiple queued rejections as well.
