### ISSUE TITLE
[transactions/{{txId}} endpoint] missing advanced details

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-client-gateway-nest#372]
Checking on UI it looks that when clicking to view the advanced details of a tx only the operation property is present.
**Steps to reproduce:**

On UI try to check the advanced details of a tx

**Actual result on nest cg:**

Check this [tx](https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev/transactions/tx?safe=eth:0xBEFA89D90c112A416139F42046Cc2d4A8a308815&id=multisig_0xBEFA89D90c112A416139F42046Cc2d4A8a308815_0x94c68fa900d9792c59261a0304033bbfc955efb2518b1b7ea853a37ace82fca0) and select to view advanced details (this should happen for every tx the safe has)

`curl --location 'https://safe-client-nest.staging.5afe.dev/v1/chains/1/transactions/multisig_0xBEFA89D90c112A416139F42046Cc2d4A8a308815_0x94c68fa900d9792c59261a0304033bbfc955efb2518b1b7ea853a37ace82fca0' \
--header 'accept: application/json'`

![Screenshot 2023-05-26 at 09 20 58](https://github.com/safe-global/safe-client-gateway-nest/assets/92332710/dfb2e4e2-1f47-4803-a11b-f8e9ad9c5227)

**Expected result on nest cg:**

Check this [tx](https://safe-wallet-web.staging.5afe.dev/transactions/tx?safe=eth:0xBEFA89D90c112A416139F42046Cc2d4A8a308815&id=multisig_0xBEFA89D90c112A416139F42046Cc2d4A8a308815_0x94c68fa900d9792c59261a0304033bbfc955efb2518b1b7ea853a37ace82fca0)

`curl --location 'https://safe-client.staging.5afe.dev/v1/chains/1/transactions/multisig_0xBEFA89D90c112A416139F42046Cc2d4A8a308815_0x94c68fa900d9792c59261a0304033bbfc955efb2518b1b7ea853a37ace82fca0' \
--header 'Accept: application/json'`

![Screenshot 2023-05-26 at 09 21 06](https://github.com/safe-global/safe-client-gateway-nest/assets/92332710/d33ddb9b-5703-4adf-8cdf-d7a540577d74)

**Comment by iamacook** [comment]
I am unable to replicate this. Are you still encountering this issue @JagoFigueroa?

**Comment by JagoFigueroa** [comment]
Can confirm that this is not an issue anymore caballero. Closing this 😉
