### ISSUE TITLE
[Delegate endpoints] Status code 400 returned

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-client-gateway-nest#387]
We seem to have an issue affecting all delegate endpoints which are returning a status code 400

Note: I am not able to test them properly from backend so the curls shared on this ticket will be a comparison for unhappy paths

Actual result on nest cg:

Request:

`curl --location --request GET 'https://safe-client-nest.staging.5afe.dev/v1/chains/1/delegates' \
--header 'Content-Type: application/json' \
--data '{
    "delegate": "foo",
    "delegator": "foo",
    "signature": 3
}'`

Response:

`{
    "message": "Validation failed",
    "code": 42,
    "arguments": []
}`

Actual result on legacy cg and the expected one for nest:

Request:

`curl --location --request GET 'https://safe-client.staging.5afe.dev/v1/chains/1/delegates' \
--header 'Content-Type: application/json' \
--data '{
    "delegate": "foo",
    "delegator": "foo",
    "signature": 3
}'`

Response:

`{
    "code": 1337,
    "message": "[\"At least one query param must be provided\"]"
}`

All delegate endpoints are affected by this:
![Screenshot 2023-06-01 at 12 30 57](https://github.com/safe-global/safe-client-gateway-nest/assets/92332710/d5cee1b2-ff65-404b-954f-2bce212740a6)

**Comment by fmrsabino** [comment]
> `curl --location --request GET 'https://safe-client-nest.staging.5afe.dev/v1/chains/1/delegates' \ --header 'Content-Type: application/json' \ --data '{ "delegate": "foo", "delegator": "foo", "signature": 3 }'`
> 
> Response:
> 
> `{ "message": "Validation failed", "code": 42, "arguments": [] }`
> 

@JagoFigueroa `GET /v1/chains/:chainId/delegates` does not expect a body in the message. Did you mean other HTTP method?

**Comment by JagoFigueroa** [comment]
This is my bad. When copying curl requests from postman there is a toggle set by default to copy every curl as a GET by default 🤦  just changed it and shouldn't happen anymore moving forward.

<img width="639" alt="Screenshot 2023-06-13 at 12 52 14" src="https://github.com/safe-global/safe-client-gateway-nest/assets/92332710/edf8bbf0-56aa-471a-b2ac-00479351a9fa">

Will do some research myself regarding this ticket and get back to you as I remember Lili saying that delegation was working nicely on mobile.

**Comment by fmrsabino** [comment]
No problem! Thank you! 🙌 Will wait for further updates!
