### ISSUE TITLE
[Get /queued] a new created tx is not returned ( caching issue ?)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway-nest#423]
Transaction service url - https://safe-transaction-goerli.staging.5afe.dev/api/v1/safes/0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c/all-transactions/?executed=false&queued=true&trusted=true - The latest tx has nonce 383

curl -X 'GET' \
  'https://safe-client-nest.staging.5afe.dev/v1/chains/5/safes/0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c/transactions/queued' \
  -H 'accept: application/json'
 Current result: The latest tx in the queued has nonce 381

2 txs with the nonce 382 and 1 tx with the nonce 383 were created after the tx with nonce 381. They are returned by the tx service but not by the Nest JS CGW 

The safe current nonce is 381

**Comment by fmrsabino** [comment]
This seems to be a caching invalidation issue. We do trigger invalidation on a `PENDING_MULTISIG_TRANSACTION`

https://github.com/safe-global/safe-client-gateway-nest/blob/46ea86df4ac9f3af839a31990c858469fd6c4028/src/routes/cache-hooks/cache-hooks.service.ts#L40-L51

The Safe Transaction Service does seems to trigger this event. This needs to be further looked into (locally) to check if the cache invalidation at this level is working correctly.

**Comment by fmrsabino** [comment]
@liliya-soroka The web hook had the wrong `chainId` configured for Goerli. It has been fixed. We should try doing this flow again on the staging instance.

**Comment by liliya-soroka** [comment]
verified, no issue in the queued list
