### ISSUE TITLE
[tx /history] Research - Completed tx taking +10 minutes to be listed on UI

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-client-gateway-nest#432]
A bit of a tricky one. While performing some tests on polygon, I received some funds on my test safe and then created a send transaction from my safe to an EOA:

![Screenshot 2023-06-13 at 14 34 27](https://github.com/safe-global/safe-client-gateway-nest/assets/92332710/746199b4-ffe8-42ae-95fd-221dd995ee8a)

Both txs took quite some time to be reflected on UI (more than 10 minutes) whereas on current staging environment they were listed without any delay. 

After talking with Fred I am opening this ticket in case further research for this case in particular would be needed.

**To reproduce this** the best way would be to sign + execute a tx or a couple from this [UI](https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev/transactions/history?safe=matic:0x6D04edC44F7C88faa670683036edC2F6FC10b86e) using the new service and compare between [current](https://safe-wallet-web.staging.5afe.dev/transactions/history?safe=matic:0x6D04edC44F7C88faa670683036edC2F6FC10b86e) staging env. There shouldn't be any big differences in regards of how much it takes for completed txs to appear listed.

**Comment by fmrsabino** [comment]
There was a misconfiguration on the web hook on the Safe Transaction Service. I've updated it to the correct value so that hooks are now triggered using the correct `chainId`

**Comment by JagoFigueroa** [comment]
Can confirm that this is fixed now, thanks! Will close the ticket 😎
