### ISSUE TITLE
[POST /{{safeAddress}}/messages/ endpoint] status code 500 returned on successful sign

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-client-gateway-nest#439]
A status code 500 is returned when signing a message with a safe owner.

**Steps to reproduce:**

On a Goerli safe with test SAFE tokens, vote on this proposal on snapshot connected via WC safe app (a bit hard to reproduce, we can look into this together if needed).

**Actual result on nest cg:**

Message is signed but a status code 500 is returned:

https://github.com/safe-global/safe-client-gateway-nest/assets/92332710/7ad4cf8c-a4f9-4e4e-a2d4-5e4d28e367d0

Note: Once the message is signed is not valid anymore and will return a status code 400 if reused. This would be an example curl that returned a 500 on signature:

`curl 'https://safe-client-nest.staging.5afe.dev/v1/chains/5/safes/0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C/messages' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Origin: https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev' \
  -H 'Referer: https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"message":{"types":{"Vote":[{"name":"from","type":"address"},{"name":"space","type":"string"},{"name":"timestamp","type":"uint64"},{"name":"proposal","type":"bytes32"},{"name":"choice","type":"uint32"},{"name":"reason","type":"string"},{"name":"app","type":"string"},{"name":"metadata","type":"string"}],"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"}]},"domain":{"name":"snapshot","version":"0.1.4"},"primaryType":"Vote","message":{"from":"0x4127839cdf4f73d9fc9a2c2861d8d1799e9df40c","space":"tutis.eth","timestamp":"1686674868","proposal":"0x28c890a25e571c766b87cd05dffa30c654786cf32f849aba66dbf52d69ad3e70","choice":"4","reason":"","app":"snapshot","metadata":"{}"}},"signature":"0xf9fb2af217ff02fcacd1579f3ce1a8575883b8fefcab62da073ba170a8097a830f85fbdb128012826bca52669ace089377dda90d09e9f7cc9a8db789b061d29a1c","safeAppId":25}' \
  --compressed`

**Expected result:**
Same as on og client gateway. Here is a curl request from staging that did not throw any errors when signing:

`curl --location --request POST 'https://safe-client.staging.5afe.dev/v1/chains/5/safes/0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C/messages' \
--header 'Accept: */*' \
--header 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
--header 'Connection: keep-alive' \
--header 'Origin: https://safe-wallet-web.staging.5afe.dev' \
--header 'Referer: https://safe-wallet-web.staging.5afe.dev/' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-site' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
--header 'content-type: application/json' \
--header 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "macOS"' \
--data '{
    "message": {
        "types": {
            "Vote": [
                {
                    "name": "from",
                    "type": "address"
                },
                {
                    "name": "space",
                    "type": "string"
                },
                {
                    "name": "timestamp",
                    "type": "uint64"
                },
                {
                    "name": "proposal",
                    "type": "bytes32"
                },
                {
                    "name": "choice",
                    "type": "uint32"
                },
                {
                    "name": "reason",
                    "type": "string"
                },
                {
                    "name": "app",
                    "type": "string"
                },
                {
                    "name": "metadata",
                    "type": "string"
                }
            ],
            "EIP712Domain": [
                {
                    "name": "name",
                    "type": "string"
                },
                {
                    "name": "version",
                    "type": "string"
                }
            ]
        },
        "domain": {
            "name": "snapshot",
            "version": "0.1.4"
        },
        "primaryType": "Vote",
        "message": {
            "from": "0x4127839cdf4f73d9fc9a2c2861d8d1799e9df40c",
            "space": "tutis.eth",
            "timestamp": "1686674123",
            "proposal": "0x28c890a25e571c766b87cd05dffa30c654786cf32f849aba66dbf52d69ad3e70",
            "choice": "4",
            "reason": "",
            "app": "snapshot",
            "metadata": "{}"
        }
    },
    "signature": "0x783f187c775baa8de46a50072f8df3cafe9f39b0ca179bf8b58b41067be0c0722d80829e9e76ae2894f19a0f7c5aca158f716995d03384269a51b1f75a32b6761c",
    "safeAppId": 25
}'`

**Comment by fmrsabino** [comment]
Currently the NestJS request returns a 400 (same as the old CGW). The difference is in how the messages are forwarded.

In the old CGW:

```json
{
    "code": 1337,
    "message": "{\"nonFieldErrors\":[\"Message with hash 0x754dfdaa5949c72e2b514f4b5377780e9f0a0c97636bfb96d1b688fb2088b219 for safe 0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C already exists in DB\"]}"
}
```

In the current CGW:

```json
{
    "code": 400,
    "message": "An error occurred"
}
```

The current CGW however does receive the same error message as the old cgw (it just maps the message to "An error occurred").

The original issue was about a `500`. @JagoFigueroa can you confirm that this is still an issue? 🙏

**Comment by JagoFigueroa** [comment]
Yes 😞 For this ticket the status code 500 is returned after a successful post/signature (when it should be a 200 instead).

The curl request shared on this ticket although it is the one that returned the 500 on the first place, as the message is already signed, when re-executing it is returning the expected 400.

**Comment by hectorgomezv** [comment]
[I've created a PR ](https://github.com/safe-global/safe-client-gateway-nest/pull/454)that potentially solves this bug by removing the validation on created messages. By this, the CGW would just return the body given by the Transaction Service without validating it (currently an empty body).
