### ISSUE TITLE
[POST messages/{{messageHash}}/signatures endpoint] status code 500 returned for unhappy path

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-client-gateway-nest#440]
Opening this as an improvement as it is the same behaviour as in our current client gateway.

When a request that is correctly formed but it will fail for this endpoint is executed, it is returning a status code 500 instead of a 400 as for our rest endpoints.

**Steps to reproduce:**

Execute this curl request, which is a valid signature that was already signed but we are reusing it and it is expected to fail:

`curl --location --request POST 'https://safe-client-nest.staging.5afe.dev/v1/chains/5/messages/0xc6b82bA149CFA113f8f48d5E3b1F78e933e16DfD/signatures' \
--header 'Content-Type: application/json' \
--data '{
    "signature": "0xb919ab2a40fd44c941949465295917524261caac1f068e66c54d6d1e8c92399a5951a66a741019635a26edcc05bac2eedb4168a72588f9169776c7cfd4eac4101c"
}'`

**Actual result:**
Status code 500 is returned.

**Expected result:**
We should avoid this 500 and return a status code 400 as with the rest of our endpoints.

Example of the same behaviour with the other post messages endpoint:

`curl --location --request POST 'https://safe-client-nest.staging.5afe.dev/v1/chains/5/safes/0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c/messages/' \
--header 'Content-Type: application/json' \
--data '{
    "message": {
        "types": {
            "Vote": [
                {
                    "name": "from",
                    "type": "address"
                },
                {
                    "name": "space",
                    "type": "string"
                },
                {
                    "name": "timestamp",
                    "type": "uint64"
                },
                {
                    "name": "proposal",
                    "type": "bytes32"
                },
                {
                    "name": "choice",
                    "type": "uint32"
                },
                {
                    "name": "reason",
                    "type": "string"
                },
                {
                    "name": "app",
                    "type": "string"
                },
                {
                    "name": "metadata",
                    "type": "string"
                }
            ],
            "EIP712Domain": [
                {
                    "name": "name",
                    "type": "string"
                },
                {
                    "name": "version",
                    "type": "string"
                }
            ]
        },
        "domain": {
            "name": "snapshot",
            "version": "0.1.4"
        },
        "primaryType": "Vote",
        "message": {
            "from": "0x4127839cdf4f73d9fc9a2c2861d8d1799e9df40c",
            "space": "tutis.eth",
            "timestamp": "1686671641",
            "proposal": "0x28c890a25e571c766b87cd05dffa30c654786cf32f849aba66dbf52d69ad3e70",
            "choice": "1",
            "reason": "",
            "app": "snapshot",
            "metadata": "{}"
        }
    },
    "signature": "0x2a50a262389a757a86117f4f6bdbe3529f2d4fd237945b5cee0e8309b40f2fb43c878c6d98f29d554a799c528745c35bbd3943c9029a72be052a31b0df137f301b",
    "safeAppId": 25
}'`

**Comment by iamacook** [comment]
You are using an address (`0xc6b82bA149CFA113f8f48d5E3b1F78e933e16DfD`) instead of a message hash. When using an address, the transaction service returns a `500` [which is why the gateway does too](https://github.com/safe-global/safe-client-gateway-nest/blob/main/src/datasources/errors/http-error-factory.ts#L22).

If you use a message hash instead, it returns a `400` (locally) and a `404` (on staging), e.g.:

```bash
curl --location --request POST 'https://safe-client-nest.staging.5afe.dev/v1/chains/5/messages/0xf345c18f67f288620d542fa0657c6044667f51c7618bc7839c5a54f2dc423d97/signatures' \ --header 'Content-Type: application/json' \ --data '{ "signature": "0xb919ab2a40fd44c941949465295917524261caac1f068e66c54d6d1e8c92399a5951a66a741019635a26edcc05bac2eedb4168a72588f9169776c7cfd4eac4101c" }'
```

**Comment by JagoFigueroa** [comment]
You are right buen hombre, I will close this. Sorry for the confusion. 

Cheers!
