### ISSUE TITLE
[Get /safes/{safeaddress} ]messages tag value is different in new NestJS in comparing with the old one

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway-nest#461]
Messages tag has diff value in the new NestJS and in the old CGW
NestJS = "messagesTag": "1687268329",
Old CGW =  "messagesTag": "1687267509",

NestJS curl 
`curl -X 'GET' \
  'https://safe-client-nest.staging.5afe.dev/v1/chains/5/safes/0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c' \
  -H 'accept: */*'`

Old CGW curl
```
curl -X 'GET' \
  'https://safe-client.staging.5afe.dev/v1/chains/5/safes/0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c' \
  -H 'accept: application/json'
```

**Comment by fmrsabino** [comment]
There are no messages for that Safe. So it returns the timestamp of when the message was generated which might be different.
