### ISSUE TITLE
[Get /safes/{safeaddress}] mobile app can not load owners because of the logo/name=null 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway-nest#462]
The mobile ios app can not load the owners' info because of the problem with parsing the response 
Most likely logo/name = null in the owners' info can not be parsed as only value is expected 
`"owners": [
        {
            "logoUri": null,
            "name": null,
            "value": "0x6eb54d4780641bbDfDDc462b7cfC5F3D54D6A41e"
        },`

NestJS curl
curl -X 'GET' \ 'https://safe-client-nest.staging.5afe.dev/v1/chains/5/safes/0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c' \ -H 'accept: */*'

Old CGW curl

curl -X 'GET' \
  'https://safe-client.staging.5afe.dev/v1/chains/5/safes/0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c' \
  -H 'accept: application/json'

**Comment by fmrsabino** [comment]
I consider this to be a bug on mobile. `null` or value absence should be considered the same from the perspective of the consumption of this API.

**Comment by elgatovital** [comment]
@liliya-soroka does this happen for both platforms: ios and android?

**Comment by elgatovital** [comment]
works on android

**Comment by fmrsabino** [comment]
Confirmed that issue is on iOS side. Closing.
