### ISSUE TITLE
Make rejectors field non-nullable

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-client-gateway-nest#551]
**Problem**

Safe Android App doesn't support `null` fields for `rejectors` field in `MultisigExecutionDetails` entity.

**Proposed solution** 
- Make `rejectors` field non-nullable.
- If no `rejectors` value applies, return it as an empty array.

**Comment by liliya-soroka** [comment]
looks good on:
- android - no crash
- ios and web - no problem with reject option or tx details in queued list
