### ISSUE TITLE
[get transactions/transfer_id] 400 - message: "transfer_id is not valid"

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway-nest#552]
URL - https://safe-client.safe.global/v1/chains/100/transactions/transfer_0x9DF58F04F3e914ED8D972146401C85313A53FecA_i12bafc5ee165d825201a24418e00bef6039bb06f6d09420ab1c5f7b4098c0809

**Comment by iamacook** [comment]
Closing as this was [fixed on the transaction service](https://github.com/safe-global/safe-transaction-service/pull/1561).
