### ISSUE TITLE
[Post /propose]422 error because the tx with nonce 26 was executed but not displayed on UI

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway-nest#562]
`https://safe-client.safe.global/v1/chains/42220/transactions/0x37a10faf7c02885Ecd041DE2F03ECD81510AeAfa/propose`

Safe:  https://app.safe.global/settings/setup?safe=celo:0x37a10faf7c02885Ecd041DE2F03ECD81510AeAfa

payload:
`{
    "to": "0x2DEf4285787d58a2f811AF24755A8150622f4361",
    "value": "0",
    "data": "0xa9059cbb00000000000000000000000037a10faf7c02885ecd041de2f03ecd81510aeafa0000000000000000000000000000000000000000000000000000041aef378da7",
    "operation": 0,
    "baseGas": "0",
    "gasPrice": "0",
    "gasToken": "0x0000000000000000000000000000000000000000",
    "refundReceiver": "0x0000000000000000000000000000000000000000",
    "nonce": "26",
    "safeTxGas": "0",
    "safeTxHash": "0x19886105e08ebc53a879de5aea3b7107c10452f6ce4d0313f0e379be274dfd86",
    "sender": "0x65F8236309e5A99Ff0d129d04E486EBCE20DC7B0",
    "signature": "0xcea5fe54e661148334d9df01f4e879cdb862cfdd8e9a143d02f6377dd7012d3d6cb074f80336bf71d3152b27c49d396bb179787aaa483c4cddba0f1a25e623561b"
}`

**Comment by fmrsabino** [comment]
Can't reproduce this one as this seems related to the cache state that was set at the time.
