### ISSUE TITLE
[get /queue] Tx created via safe-app doesn't have safe info

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway-nest#599]
https://safe-client.safe.global/v1/chains/5/safes/0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c/transactions/queued - tx with nonce 448 is created using CowSwap and should have safe apps info, but it's empty

Could you make sure that:
1. if the tx created via safe apps CGW takes information from the frontend about the safe app that was used
2. The safe app info is returned if the tx was created using safe-app on UI

**Comment by hectorgomezv** [comment]
Closing this since I think it was fixed by https://github.com/safe-global/safe-client-gateway-nest/pull/600
